name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: bun run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: bun run lint

  run-action:
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Print Secret
        run: echo "${EXAMPLE_SECRET}"
        env:
          EXAMPLE_SECRET: ${{ secrets.EXAMPLE_SECRET }}
      - name: Print Secret with Action
        uses: ./
        with:
          secret: ${{ secrets.EXAMPLE_SECRET }}

      - name: Print Multiline Secret
        run: echo "${MULTILINE_SECRET}"
        env:
          MULTILINE_SECRET: ${{ secrets.MULTILINE_SECRET }}
      - name: Print Multiline Secret with Action
        uses: ./
        with:
          secret: ${{ secrets.MULTILINE_SECRET }}
