name: Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: koki-develop/unmask-secret-action@v1
        with:
          secret: ${{ secrets.EXAMPLE_SECRET }}
