name: Major Version Sync
run-name: Major Version Sync - ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  major-version-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: koki-develop/major-version-sync@b86eb31aef1c06d81f133799b35ace3c80ebdf0a # v1.2.0
        with:
          token: ${{ github.token }}
